config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "elimination_operation" => "static_pages#elimination_operation"
  get "roundrobin_operation" => "static_pages#roundrobin_operation"
  get "inquiry" => "static_pages#inquiry"

  resources :eliminations, except: :index do
    resource :draw, only: [:show], module: :eliminations
    resource :authentication, only: [:new, :create], module: :eliminations
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_eliminations' => 'eliminations#index'

  resources :roundrobins, except: :index do
    resource :draw, only: [:show, :update], module: :roundrobins
    resource :ranking, only: [:show], module: :roundrobins
    resource :authentication, only: [:new, :create], module: :roundrobins
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_roundrobins' => 'roundrobins#index'

  resources :tournaments, only: [:index] do
    namespace :teams do
      resource :shuffle, only: [:create]
      resource :bulk_update, only: [:create]
    end
    resources :teams, except: :show
    resources :games
    resource :bookmark, only: [:create, :destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def elimination_operation
  end

  def roundrobin_operation
  end
  def inquiry
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_elimination_basic_manual.html.erb
<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step1</h5>
    <div class="border demo mb-3">
      <%= image_tag('create_elimination.PNG', width: '100%') %>
    </div>
    <p>
      「トーナメント表作成」ボタンをクリック。<br>
      大会名、参加チーム数を入力します。
    </p>
  </div>
</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step2</h5>
    <p>
      <span class="badge bg-dark">トーナメント表</span>
    </p>
    <div class="border demo mb-2">
      <%= image_tag('elimination.PNG', width: '100%') %>
    </div>
    <p>トーナメントが作成されます。</p>
  </div>
</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step3</h5>
    <p><span class="badge bg-dark">チーム</span></p>
    <div class="border demo mb-3">
      <%= image_tag('elimination_team_update.PNG', width: '100%') %>
    </div>
    <p>
      チーム名、アイコンを必要に応じて変更します。
    </p>
  </div>

</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step4</h5>
    <p>
      <span class="badge bg-dark">トーナメント表</span>
    </p>
    <div class="border demo mb-3">
      <%= image_tag('elimination_game_update.PNG', width: '100%') %>
    </div>
    <p>
      対象の試合(黄色のマス)をクリックして、試合結果を入力します。
    </p>
  </div>
</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step5</h5>
    <p>
      <span class="badge bg-dark">トーナメント表</span>
    </p>
    <div class="border demo mb-2">
      <%= image_tag('elimination-finished.PNG', width: '100%') %>
    </div>
    <p>トーナメント表が更新されます。</p>
  </div>
</div>

app/views/static_pages/_roundrobin_basic_manual.html.erb
<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step1</h5>
    <div class="border demo mb-3">
      <%= image_tag('create_roundrobin.PNG', width: '100%') %>
    </div>
    <p>
      「リーグ表作成」ボタンをクリック。<br>
      大会名、参加チーム数を入力します。
    </p>
  </div>
</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step2</h5>
    <p>
      <span class="badge bg-dark">リーグ表</span><br>
    </p>
    <div class="border demo mb-3">
      <%= image_tag('roundrobin.PNG', width: '100%') %>
    </div>
    <p>リーグ表が作成されます。</p>
  </div>
</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step3</h5>
    <p><span class="badge bg-dark">チーム</span></p>
    <div class="border demo mb-3">
      <%= image_tag('roundrobin_team_update.PNG', width: '100%') %>
    </div>
    <p>
      チーム名、アイコンを必要に応じて変更します。
    </p>
  </div>

</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step4</h5>
    <p>
      <span class="badge bg-dark">リーグ表</span><br>
    </p>
    <div class="border demo mb-3">
      <%= image_tag('roundrobin_game_update.PNG', width: '100%') %>
    </div>
    <p>
      対象の試合(黄色のマス)をクリックして、試合結果を入力します。
    </p>
  </div>
</div>

<div class="container-lg py-3">
  <div class="d-flex flex-column align-items-center gap-2">
    <h5 class="text-main">Step5</h5>
    <p>
      <span class="badge bg-dark">リーグ表</span>
    </p>
    <div class="border demo mb-3">
      <%= image_tag('roundrobin-finished.PNG', width: '100%') %>
    </div>
    <p>
      <span class="badge bg-dark">順位表</span>
    </p>
    <div class="border demo mb-3">
      <%= image_tag('ranking-finished.PNG', width: '100%') %>
    </div>
    <p>リーグ表/順位表が更新されます。</p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% set_meta_tags reverse: false %>

<div id="main_visual" class="text-center">
  <div class="container-lg py-3">

    <h1 id="logo" class="display-3">Tournament Note</h1>
    <p class="fw-bold">トーナメント表・リーグ表 作成</p>

    <div class="d-inline-flex flex-column flex-md-row justify-content-center gap-3">
      <%= link_to "トーナメント表作成", new_elimination_path, class: "btn btn-main btn-lg text-white" %>
      <%= link_to "リーグ表作成", new_roundrobin_path, class: "btn btn-main btn-lg text-white" %>
    </div>

  </div>
</div>



<div class="container-lg py-3 my-3">
  <p class="text-center"><u>スポーツ、ゲーム等の対戦記録に</u></p>
  <div class="d-flex flex-column align-items-center">
    <ul>
      <li class="mb-2">Tournament Noteは、トーナメント表/リーグ表 を作成するWebアプリです。</li>
      <li class="mb-2">ユーザ登録不要。</li>
      <li class="mb-2">全て無料で使えます。</li>
      <li class="mb-2">作成した表は、仲間と簡単に共有できます。</li>
    </ul>
  </div>

</div>


<div class="accordion" id="accordion">
<%# ----------------- トーナメント表 ------------------------- %>
  <div class="accordion-item">
    <div class="accordion-header" id="elimination-header">
      <h5 class="mb-0">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#elimination-collapse" aria-expanded="true" aria-controls="elimination-collapse">
          トーナメント表
        </button>
      </h5>
    </div>

    <div id="elimination-collapse" class="accordion-collapse collapse show" aria-labelledby="elimination-header">
      <div class="accordion-body">
        <div class="d-flex flex-column align-items-center gap-2">

          <div class="border demo mb-2">
            <%= image_tag('Manual-Elimination.png', width: 386, height: 330) %>
          </div>

          <div class="d-flex justify-content-center">
            <ul>
              <li>参加チーム数： 2〜16チーム</li>
              <li>参加チーム数に合わせて自動生成。<br>(チーム数が端数でも設定不要)</li>
            </ul>
          </div>

        </div>
      </div>
    </div>
  </div>

  <%# ----------------- リーグ表 ------------------------- %>
  <div class="accordion-item">
    <div class="accordion-header" id="roundrobin-header">
      <h5 class="mb-0">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#roundrobin-collapse" aria-expanded="true" aria-controls="roundrobin-collapse">
          リーグ表
        </button>
      </h5>
    </div>

    <div id="roundrobin-collapse" class="accordion-collapse collapse show" aria-labelledby="roundrobin-header">
      <div class="accordion-body">
        <div class="d-flex flex-column align-items-center gap-2">

          <div class="border demo mb-3">
            <%= image_tag('Manual-Roundrobin.png', width: 386, height: 423) %>
          </div>

          <div class="border demo mb-3">
            <%= image_tag('Manual-Ranking.png', width: 386, height: 249) %>
          </div>

          <div class="d-flex justify-content-center">
            <ul>
              <li>参加チーム数： 2〜16チーム</li>
              <li>繰り返し対戦可能。</li>
              <li>勝点、勝率など順位条件を指定可能。</li>
            </ul>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/inquiry.html.erb
<% set_meta_tags title: 'お問い合わせ', og: { title: 'お問い合わせ' } %>

<div class="container-lg mt-3 mb-5">
  <h1 class="mb-5"><%= "お問い合わせ" %></h1>
  <p>
    お問い合わせは下記までお願いします。<br>
  </p>
  <div class="alert alert-light">
    tournamentnote@gmail.com
  </div>
</div>