config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "elimination_operation" => "static_pages#elimination_operation"
  get "roundrobin_operation" => "static_pages#roundrobin_operation"
  get "inquiry" => "static_pages#inquiry"

  resources :eliminations, except: :index do
    resource :draw, only: [:show], module: :eliminations
    resource :authentication, only: [:new, :create], module: :eliminations
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_eliminations' => 'eliminations#index'

  resources :roundrobins, except: :index do
    resource :draw, only: [:show, :update], module: :roundrobins
    resource :ranking, only: [:show], module: :roundrobins
    resource :authentication, only: [:new, :create], module: :roundrobins
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_roundrobins' => 'roundrobins#index'

  resources :tournaments, only: [:index] do
    namespace :teams do
      resource :shuffle, only: [:create]
      resource :bulk_update, only: [:create]
    end
    resources :teams, except: :show
    resources :games
    resource :bookmark, only: [:create, :destroy]
  end
end

app/views/shared/_bookmark_menu.html.erb
<% if bookmarked_tournaments.present? %>
  <div class="nav-item dropdown">
    <button id="dropdown-bookmark" class="navbar-toggler dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
      <span><i class="bi bi-star-fill"></i></span>
    </button>

    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-bookmark">
      <% bookmarked_tournaments.each do |tournament_id| %>
        <%= link_to tournament_name(tournament_id), tournament_path(tournament_id), class: "dropdown-item", data: { turbo_frame: "_top" } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_elimination_header.html.erb
<div class="container-lg mt-3 mb-5">
  <div class="d-flex align-items-center gap-3">
    <h1 class="mb-3"><%= elimination.name %></h1>
    <p id="elimination-status" class="lead" data-testid="tournament-status"><%= span_tag__status(elimination) %></p>
  </div>
  <div class="btn-group">
    <% if tournament_owner?(elimination.tournament) %>
      <%= link_to "設定", edit_elimination_path(elimination), class: "btn btn-outline-dark #{'active' if current_page == '設定'}" %>
      <%= link_to "チーム", tournament_teams_path(elimination.tournament), class: "btn btn-outline-dark #{'active' if current_page == 'チーム'}" %>
    <% end %>
    <%= link_to "トーナメント表", elimination_draw_path(elimination), class: "btn btn-outline-dark #{'active' if current_page == 'トーナメント表'}" %>
    <%= link_to "共有", share_elimination_path(elimination), class: "btn btn-outline-dark #{'active' if current_page == '共有'}" %>
    <% unless tournament_owner?(elimination.tournament) %>
      <%= link_to "更新", new_elimination_authentication_path(elimination), class: "btn btn-outline-dark #{'active' if current_page == '更新'}" %>
    <% end %>
  </div>
</div>

app/views/shared/_roundrobin_header.html.erb
<div class="container-lg mt-3 mb-5">
  <div class="d-flex align-items-center gap-3">
    <h1 class="mb-3"><%= roundrobin.name %></h1>
    <p id="roundrobin-status" class="lead" data-testid="tournament-status"><%= span_tag__status(roundrobin) %></p>
  </div>
  <div class="btn-group">
    <% if tournament_owner?(roundrobin.tournament) %>
      <%= link_to "設定", edit_roundrobin_path(roundrobin), class: "btn btn-outline-dark #{'active' if current_page == '設定'}" %>
      <%= link_to "チーム", tournament_teams_path(roundrobin.tournament), class: "btn btn-outline-dark #{'active' if current_page == 'チーム'}" %>
    <% end %>
    <%= link_to "リーグ表", roundrobin_draw_path(roundrobin), class: "btn btn-outline-dark #{'active' if current_page == 'リーグ表'}" %>
    <%= link_to "順位表", roundrobin_ranking_path(roundrobin), class: "btn btn-outline-dark #{'active' if current_page == '順位表'}" %>
    <%= link_to "共有", share_roundrobin_path(roundrobin), class: "btn btn-outline-dark #{'active' if current_page == '共有'}" %>
    <% unless tournament_owner?(roundrobin.tournament) %>
      <%= link_to "更新", new_roundrobin_authentication_path(roundrobin), class: "btn btn-outline-dark #{'active' if current_page == '更新'}" %>
    <% end %>
  </div>
</div>