config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "elimination_operation" => "static_pages#elimination_operation"
  get "roundrobin_operation" => "static_pages#roundrobin_operation"
  get "inquiry" => "static_pages#inquiry"

  resources :eliminations, except: :index do
    resource :draw, only: [:show], module: :eliminations
    resource :authentication, only: [:new, :create], module: :eliminations
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_eliminations' => 'eliminations#index'

  resources :roundrobins, except: :index do
    resource :draw, only: [:show, :update], module: :roundrobins
    resource :ranking, only: [:show], module: :roundrobins
    resource :authentication, only: [:new, :create], module: :roundrobins
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_roundrobins' => 'roundrobins#index'

  resources :tournaments, only: [:index] do
    namespace :teams do
      resource :shuffle, only: [:create]
      resource :bulk_update, only: [:create]
    end
    resources :teams, except: :show
    resources :games
    resource :bookmark, only: [:create, :destroy]
  end
end

app/models/roundrobin.rb
class Roundrobin < ApplicationRecord
  belongs_to :tournament
  delegate :teams, to: :tournament
  delegate :games, to: :tournament

  validates :name, presence: true, length: { maximum: 16 }
  validates :has_score, inclusion: { in: [true, false] }
  validates :num_of_round, numericality: { only_integer: true, in: 1..10 }
  validates :password, length: { maximum: 16 }

  # Constant
  enum rank1: { none: 0, win_points: 1, win_rate: 2, goal_diff: 11, total_goals: 12, head_to_head: 90 }, _prefix: true
  enum rank2: { none: 0, win_points: 1, win_rate: 2, goal_diff: 11, total_goals: 12, head_to_head: 90 }, _prefix: true
  enum rank3: { none: 0, win_points: 1, win_rate: 2, goal_diff: 11, total_goals: 12, head_to_head: 90 }, _prefix: true
  enum rank4: { none: 0, win_points: 1, win_rate: 2, goal_diff: 11, total_goals: 12, head_to_head: 90 }, _prefix: true

  RANKING_CRITERIA = {
    'none' => 'なし',
    'win_points' => '勝点',
    'win_rate' => '勝率',
    'goal_diff' => '得失点差',
    'total_goals' => '総得点',
    'head_to_head' => '直接対決',
  }


  def status
    if games.count == 0
      sts = "NOT_STARTED"
    elsif games.count >= (1..(teams.size-1)).sum * num_of_round
      sts = "FINISHED"
    else
      sts = "ONGOING"
    end
    sts
  end

end

app/controllers/roundrobins/authentications_controller.rb
class Roundrobins::AuthenticationsController < ApplicationController
  def new
    @roundrobin = Roundrobin.find_by(id: params[:roundrobin_id])
  end

  def create
    @roundrobin = Roundrobin.find_by(id: params[:roundrobin_id])
    unless @roundrobin
      flash[:warning] = "リーグが見つかりません。"
      redirect_to root_path and return
    end

    @error_message = nil
    if @roundrobin.password == params[:password]
      authenticaion = Authentication.new(cookies)
      authenticaion.set_password(id: @roundrobin.id, tournament_type: 'roundrobin', password: params[:password])

      redirect_to roundrobin_draw_path(@roundrobin)
    else
      @error_message = "パスワードが不一致です"

      render 'new', status: :unprocessable_entity
    end
  end
end

app/controllers/roundrobins/draws_controller.rb
class Roundrobins::DrawsController < ApplicationController
  def show
    roundrobin = Roundrobin.find_by(id: params[:roundrobin_id])
    unless roundrobin
      flash[:warning] = "リーグが見つかりません。"
      redirect_to root_path and return
    end
    roundrobin.tournament.update_last_access_day

    @round = 1
    @roundrobin = RoundrobinDecorator.new(roundrobin)
  end

  def update
    roundrobin = Roundrobin.find_by(id: params[:roundrobin_id])
    unless roundrobin
      flash[:warning] = "リーグが見つかりません。"
      redirect_to root_path and return
    end

    @round = params[:round].to_i
    @roundrobin = RoundrobinDecorator.new(roundrobin)
  end

end

app/controllers/roundrobins/rankings_controller.rb
class Roundrobins::RankingsController < ApplicationController

  def show
    @roundrobin = Roundrobin.find_by(id: params[:roundrobin_id])
    unless @roundrobin
      flash[:warning] = "リーグが見つかりません。"
      redirect_to root_path and return
    end

    @ranking = Ranking.new(@roundrobin).decorate
  end

end

app/controllers/roundrobins_controller.rb
class RoundrobinsController < ApplicationController
  before_action :authenticate_owner, only: [:edit, :update, :destroy, :reset]

  def index
    @num_of_roundrobins = Roundrobin.all.size
    @roundrobins = Roundrobin.all.order(created_at: :desc).page(params[:page])
  end

  def show
    redirect_to roundrobin_draw_path(params[:id])
  end

  def new
    @roundrobin = Roundrobin.new
  end

  def create
    ActiveRecord::Base.transaction do
      tournament = Tournament.create(tournament_type: :roundrobin)
      @roundrobin = tournament.build_roundrobin(roundrobin_params)
      num_of_teams = params[:num_of_teams].to_i

      if @roundrobin.save
        authenticaion = Authentication.new(cookies)
        authenticaion.set_password(id: @roundrobin.id, tournament_type: 'roundrobin', password: @roundrobin.password)

        (1..num_of_teams).each do |i|
          @roundrobin.teams.create(name: "Team#{i}", entryNo: i)
        end
        redirect_to roundrobin_draw_path(@roundrobin)
      else
        render 'new', status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end
    end
  end

  def edit
    @roundrobin = Roundrobin.find_by(id: params[:id])
    unless @roundrobin
      flash[:warning] = "リーグが見つかりません。"
      redirect_to root_path
    end
  end

  def update
    @roundrobin = Roundrobin.find_by(id: params[:id])

    if @roundrobin.update(roundrobin_params)
      authenticaion = Authentication.new(cookies)
      authenticaion.set_password(id: @roundrobin.id, tournament_type: 'roundrobin', password: @roundrobin.password)

      redirect_to roundrobin_draw_path(@roundrobin)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @roundrobin = Roundrobin.find_by(id: params[:id])
    @roundrobin.tournament.destroy
    authenticaion = Authentication.new(cookies)
    authenticaion.clear_password(id: @roundrobin.id, tournament_type: 'roundrobin')

    redirect_to root_path, flash: { info: 'リーグを削除しました' }
  end

  def reset
    @roundrobin = Roundrobin.find_by(id: params[:id])
    @roundrobin.games.delete_all

    redirect_to roundrobin_draw_path(@roundrobin), flash: { info: 'リーグをリセットしました' }
  end

  def share
    @roundrobin = Roundrobin.find_by(id: params[:id])
  end


  ### Private Method
  private

  def roundrobin_params
    ret_p = params.require(:roundrobin).permit(:name, :description, :has_score, :num_of_round, :rank1, :rank2, :rank3, :rank4, :password)
    if ret_p[:name].blank?
      ret_p[:name] = "#{Date.today}"
    end
    ret_p
  end



  def authenticate_owner
    roundrobin = Roundrobin.find_by(id: params[:id])
    unless view_context.tournament_owner?(roundrobin.tournament)
      redirect_to roundrobin_draw_path(roundrobin)
    end
  end

end

app/helpers/roundrobins_helper.rb
module RoundrobinsHelper

  def div_tag__ranking_criteria(form:, priority:, items:)
    case priority
      when 1
        rankx_column = @roundrobin.rank1
        rankx_symbol = :rank1
      when 2
        rankx_column = @roundrobin.rank2
        rankx_symbol = :rank2
      when 3
        rankx_column = @roundrobin.rank3
        rankx_symbol = :rank3
      when 4
        rankx_column = @roundrobin.rank4
        rankx_symbol = :rank4
    end

    array = items.map { |item| [Roundrobin::RANKING_CRITERIA[item], item] }

    tag.div(class: ['col-6 col-md-3 mb-3'], data: { testid: "ranking-criteria#{priority}" }) {
      concat(tag.div {
        concat form.label(rankx_symbol, "順位条件#{priority}", class: 'form-control-label')
        concat form.select(rankx_symbol, options_for_select(array, rankx_column), {}, class: ['form-control'])
      })
    }
  end

end

app/views/roundrobins/_ranking_table.html.erb
<div class="overflow-auto mb-3">
  <table id="ranking-table" class="table sticky-table table-bordered text-center">
    <thead>
      <tr>
        <th>順位</th>
        <th>チーム</th>
        <% if roundrobin.rank_by?('win_points') %>
          <th>勝点</th>
        <% end %>
        <% if roundrobin.rank_by?('win_rate') %>
          <th>勝率</th>
        <% end %>
        <th>勝</th>
        <th>分</th>
        <th>敗</th>
        <% if roundrobin.has_score %>
          <th>得点</th>
          <th>失点</th>
          <th>得失差</th>
        <% end %>
      </tr>
    </thead>

    <%= tbody_tag__ranking(roundrobin:, ranking:, teams:) %>
  </table>
</div>

<div>
  <p class="mb-2">
    <span><i class="bi bi-diamond-fill"></i></span>
    順位条件
  </p>
  <ol>
    <% if roundrobin.rank1 != 'none' %>
      <li><%= Roundrobin::RANK_CONDITION[roundrobin.rank1] %></li>
    <% end %>
    <% if roundrobin.rank2 != 'none' %>
      <li><%= Roundrobin::RANK_CONDITION[roundrobin.rank2] %></li>
    <% end %>
    <% if roundrobin.rank3 != 'none' %>
      <li><%= Roundrobin::RANK_CONDITION[roundrobin.rank3] %></li>
    <% end %>
    <% if roundrobin.rank4 != 'none' %>
      <li><%= Roundrobin::RANK_CONDITION[roundrobin.rank4] %></li>
    <% end %>
  </ol>
</div>

app/views/roundrobins/_roundrobin.html.erb
<div class="col-md-6 mb-2">
  <div class="card bg-light">
    <%= link_to roundrobin_draw_path(roundrobin), class: "card-body text-decoration-none" do %>
      <div class="d-flex justify-content-between">
        <p class="card-title"><%= roundrobin.name %>　<%= span_tag__status(roundrobin) %></p>
        <i class="bi bi-chevron-right"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/roundrobins/_roundrobin_table.html.erb
<table id="roundrobin-table" class="roundrobin-table table table-bordered text-center">
  <thead>
    <tr>
      <th class="no-game-cell"></th>
      <% teams.each do |team| %>
        <th>
          <%= team_uniform(team) %>
          <div><%= team_name(team) %></div>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% teams.each do |team| %>
      <%= tr_tag__team(roundrobin:, teams:, games:, round:, current_team: team) %>
    <% end %>
  </tbody>
</table>

app/views/roundrobins/admin.html.erb
<% set_meta_tags title: @roundrobin.name, og: { title: @roundrobin.name } %>

<%# トーナメント共通ヘッダ %>
<%= render "shared/roundrobin_header", { roundrobin: @roundrobin, current_page: "更新" } %>

<div class="container-lg my-3">

  <p> この大会は、作成者にパスワードで保護されています。 </p>
  <div class="border border-dark p-4">
  <%= turbo_frame_tag "form" do %>
    <%= form_with(url: authentication_roundrobin_path(@roundrobin), id: "password_form", data: { turbo_frame: "_top" }) do |form| %>
      <%# Error Message %>
      <% if @error_message %>
        <div class="alert alert-danger mb-4">
          <%= @error_message %>
        </div>
      <% end %>

      <%# パスワード %>
      <%= label_tag(:password, "更新パスワード", class: "form-control-label text-dark text-nowrap") %>
      <div class="mb-1 d-flex justify-content-between align-items-center gap-2">

        <div class="">
          <%= text_field_tag(:password, "", class: "form-control") %>
        </div>
        <div class="">
          <%= form.submit('送信', class: "btn btn-secondary") %>
        </div>
      </div>

      <%# Submit %>

    <% end %>
  <% end %>
  </div>
</div>

app/views/roundrobins/edit.html.erb
<% set_meta_tags title: @roundrobin.name, og: { title: @roundrobin.name } %>

<%# リーグ共通ヘッダ %>
<%= render "shared/roundrobin_header", { roundrobin: @roundrobin, current_page: "設定" } %>

<div class="container-lg bg-light py-3">
  <%# 変更フォーム %>
  <div class="mb-4">
    <%= form_with(model: @roundrobin, id: "edit-roundrobin") do |form| %>
      <%# Error Message %>
      <%= form_error_notification(@roundrobin) %>

      <%# 大会名 %>
      <div class="mb-4">
        <%= form.label(:name, "大会名", class: "form-control-label") %>
        <%= form.text_field(:name, class: "form-control", placeholder: "(空の場合は、本日の日付が入ります。)") %>
      </div>

      <%# 説明 %>
      <div class="mb-4">
        <%= form.label(:description, "説明", class: "form-control-label") %>
        <%= form.text_area(:description, rows: 5, cols: 10, class: "form-control", placeholder: "(省略可能)") %>
      </div>

      <%# スコア有無 %>
      <div class="form-check mb-4">
        <%= form.check_box :has_score, { class: 'form-check-input' } %>
        <%= form.label :has_score, "スコアを記録", class: "form-check-label" %>
      </div>

      <%# Round数 %>
      <div class="mb-4">
        <div>
          <%= form.label(:num_of_round, " 対戦数", class: "form-control-label") %>
          <div class="d-flex flex-row align-items-end gap-2">
            <%= form.select :num_of_round, options_for_select(1..10, @roundrobin.num_of_round), {}, { class: "form-control w-25" } %>
            <span> 周</span>
          </div>
        </div>
      </div>

      <%# 順位判定条件 %>
      <div class="row mb-4">
        <%= div_tag__ranking_criteria(form: form, priority: 1, items: ['win_points', 'win_rate', 'goal_diff', 'total_goals']) %>
        <%= div_tag__ranking_criteria(form: form, priority: 2, items: ['none', 'win_points', 'win_rate', 'goal_diff', 'total_goals', 'head_to_head']) %>
        <%= div_tag__ranking_criteria(form: form, priority: 3, items: ['none', 'win_points', 'win_rate', 'goal_diff', 'total_goals', 'head_to_head']) %>
        <%= div_tag__ranking_criteria(form: form, priority: 4, items: ['none', 'win_points', 'win_rate', 'goal_diff', 'total_goals', 'head_to_head']) %>
      </div>

      <%# 更新パスワード %>
      <div class="mb-4">
        <%= form.label(:password, "更新パスワード", class: "form-control-label") %>
        <% tooltip_title = "共有する相手に更新を許可しない場合、本パスワードを設定してください。" %>
        <span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title=<%= tooltip_title %>><i class="bi bi-question-square-fill"></i></span>
        <%= form.text_field(:password, class: "form-control", placeholder: "(空の場合は、他のブラウザからも更新可能です。)") %>
      </div>

      <%# 更新ボタン %>
      <div class="d-flex mt-4 justify-content-end">
        <div class="bg-white">
          <%= form.submit("更新", class: "btn btn-outline-main") %>
        </div>
      </div>
    <% end %>
  </div>

  <hr>

  <%# リセット %>
  <div class="mb-4">
    <h5 class="text-danger">リーグをリセット</h5>
    <p>試合結果を削除して、リーグ開始前の状態に戻します。</p>
    <div class="d-flex justify-content-end">
      <div class="bg-white">
        <%= button_to "リセット", reset_roundrobin_path(@roundrobin), class: "btn btn-outline-danger",
                      data: { turbo_confirm: "全試合結果を削除します。" } %>
      </div>
    </div>
  </div>

  <hr>

  <%# 削除 %>
  <div class="mb-4">
    <h5 class="text-danger">リーグを削除</h5>
    <div class="d-flex justify-content-end">
      <div class="bg-white">
        <%= button_to "削除", roundrobin_path(@roundrobin), class: "btn btn-outline-danger",
                      method: :delete,
                      data: { turbo_confirm: "「#{@roundrobin.name}」リーグを削除します。削除すると元には戻せません。" } %>
      </div>
    </div>
  </div>
</div>

app/views/roundrobins/index.html.erb
<% set_meta_tags title: 'リーグ一覧', og: { title: 'リーグ一覧' } %>

<div class="container-lg my-3">
  <h1 class="mb-4">リーグ一覧</h1>

  <% if @roundrobins.present? %>
    <p class="lead"><%= "リーグ数: #{@num_of_roundrobins}" %></p>
    <div class="row mb-4">
      <%= render @roundrobins %>
    </div>
    <div class="d-flex justify-content-center">
      <%= paginate @roundrobins, theme: 'bootstrap-5' %>
    </div>
  <% else %>
    <div class="alert alert-warning">リーグは未登録です</div>
  <% end %>
</div>

app/views/roundrobins/new.html.erb
<% set_meta_tags title: 'リーグ表作成', og: { title: 'リーグ表作成' } %>

<div class="container-lg my-3">
  <h1 class="mb-5">リーグ表作成</h1>
</div>


<div class="container-lg bg-light py-3">

  <%= form_with(model: @roundrobin, id: "new-roundrobin") do |form| %>
    <%# Error Message %>
    <%= form_error_notification(@roundrobin) %>

    <%# 大会名 %>
    <div class="mb-4">
      <%= form.label(:name, "大会名", class: "form-control-label") %>
      <%= form.text_field(:name, class: "form-control", placeholder: "(空の場合は、本日の日付が入ります。)") %>
    </div>

    <%# 説明 %>
<!--    <div class="mb-4">-->
      <%#= form.label(:description, "説明", class: "form-control-label") %>
      <%#= form.text_area(:description, rows: 5, cols: 10, class: "form-control", placeholder: "(省略可能)") %>
<!--    </div>-->

    <%# チーム数 %>
    <div class="mb-4">
      <%= label_tag :num_of_teams, "参加チーム数", class: "form-control-label" %>
      <%= select_tag :num_of_teams, options_for_select(1..MAX_TEAMS, 4), { class: "form-control" } %>
    </div>

    <hr>
    <p class="text-secondary mb-4">
      <span><i class="bi bi-diamond-fill"></i></span>
      詳細設定
    </p>

    <%# スコア有無 %>
    <div class="form-check mb-4">
      <%= form.check_box :has_score, { class: 'form-check-input' } %>
      <%= form.label :has_score, "スコアを記録", class: "form-check-label" %>
    </div>

    <%# Round数 %>
    <div class="mb-4">
      <div>
        <%= form.label(:num_of_round, " 対戦数", class: "form-control-label") %>
        <div class="d-flex flex-row align-items-end gap-2">
          <%= form.select :num_of_round, options_for_select(1..10, @roundrobin.num_of_round), {}, { class: "form-control w-25" } %>
          <span> 周</span>
        </div>
      </div>
    </div>

    <%# 順位判定条件 %>
    <div class="row mb-4">
      <%= div_tag__ranking_criteria(form: form, priority: 1, items: ['win_points', 'win_rate', 'goal_diff', 'total_goals']) %>
      <%= div_tag__ranking_criteria(form: form, priority: 2, items: ['none', 'win_points', 'win_rate', 'goal_diff', 'total_goals', 'head_to_head']) %>
      <%= div_tag__ranking_criteria(form: form, priority: 3, items: ['none', 'win_points', 'win_rate', 'goal_diff', 'total_goals', 'head_to_head']) %>
      <%= div_tag__ranking_criteria(form: form, priority: 4, items: ['none', 'win_points', 'win_rate', 'goal_diff', 'total_goals', 'head_to_head']) %>
    </div>

    <%# 更新パスワード %>
<!--    <div class="mb-4">-->
      <%#= form.label(:password, "更新パスワード", class: "form-control-label") %>
      <%# tooltip_title = "共有する相手に更新を許可しない場合、本パスワードを設定してください。" %>
<!--      <span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title=<%#= tooltip_title %>><i class="bi bi-question-square-fill"></i></span>-->
      <%#= form.text_field(:password, class: "form-control", placeholder: "(空の場合は、他のブラウザからも更新可能です。)") %>
<!--    </div>-->

    <%# 作成ボタン %>
    <div class="d-flex mt-4 justify-content-end">
      <div class="bg-white">
        <%= form.submit("作成", class: "btn btn-outline-main") %>
      </div>
    </div>

  <% end %>
</div>

app/views/roundrobins/ranking.html.erb
<% set_meta_tags title: @roundrobin.name, og: { title: @roundrobin.name } %>

<%# リーグ共通ヘッダ %>
<%= render "shared/roundrobin_header", { roundrobin: @roundrobin, current_page: "順位表" } %>

<%# 参加チームなしの場合 %>
<% if @teams.count < 2 %>
  <div class="container-lg my-3">
    <div class="alert alert-warning">参加チームが2チーム以上必要です</div>
  </div>

<% else %>
  <div class="bg-white">
    <div class="container-lg my-3 py-3">
        <%= render partial: "roundrobins/ranking_table",
                   locals: { roundrobin: @roundrobin, ranking: @ranking, teams: @teams } %>
    </div>
  </div>

<% end %>

app/views/roundrobins/share.html.erb
<% set_meta_tags title: @roundrobin.name, og: { title: @roundrobin.name } %>

<%# トーナメント共通ヘッダ %>
<%= render "shared/roundrobin_header", { roundrobin: @roundrobin, current_page: "共有" } %>

<div class="container-lg my-3">
  <p class="fw-bold">この大会のURL</p>
  <p>後でアクセスするときや、他の人と共有するにはこのURLを使用します。</p>
  <div class="alert alert-light overflow-x-scroll">
    <%= roundrobin_url(@roundrobin) %>
  </div>
</div>

app/views/roundrobins/show.html.erb
<% set_meta_tags title: @roundrobin.name, og: { title: @roundrobin.name } %>

<%# リーグ共通ヘッダ %>
<%= render "shared/roundrobin_header", { roundrobin: @roundrobin, current_page: "リーグ表" } %>

<%# Bookmarkボタン %>
<%= turbo_frame_tag "bookmark_button" do %>
  <%= render "bookmarks/bookmark_button", { bookmarked_tournaments: @bookmarked_tournament_ids, tournament: @roundrobin.tournament } %>
<% end %>

<%# トーナメント説明 %>
<% if @roundrobin.description.present? %>
  <div class="bg-light my-5">
    <div class="container-lg py-3">
      <p class="pre-wrap"><%= raw Rinku.auto_link(@roundrobin.description, :urls, 'target="_blank" rel="noopener noreferrer"') %></p>
    </div>
  </div>
<% end %>

<%# 参加チームなしの場合 %>
<% if @teams.count < 2 %>
  <div class="container-lg my-3">
    <div class="alert alert-warning">参加チームが2チーム以上必要です</div>
  </div>

<% else %>
  <div class="bg-white">
    <div class="container-lg my-3 py-3">

      <%# 更新方法説明 (パスワード保護解除時のみ) %>
      <% if tournament_owner?(@roundrobin.tournament) %>
        <p>
          各試合をクリックして、試合結果を更新します。
          <% tooltip_title = "下のリーグ表の各試合(薄い黄色部分)をクリック" %>
          <span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title=<%= tooltip_title %>>
            <i class="bi bi-question-square-fill"></i>
          </span>
        </p>
      <% end %>

      <%# Round選択 %>
      <%= turbo_frame_tag "round_select" do %>
        <%= render partial: "roundrobins/round_select", locals: { roundrobin: @roundrobin, round: @round } %>
      <% end %>

      <%# 対戦表 %>
      <div class="roundrobin-table-wrapper">
        <%= render partial: "roundrobins/roundrobin_table",
                   locals: { roundrobin: @roundrobin, teams: @teams, games: @games, round: @round } %>
      </div>

    </div>
  </div>

  <%= turbo_frame_tag "modal" %>
<% end %>