config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "elimination_operation" => "static_pages#elimination_operation"
  get "roundrobin_operation" => "static_pages#roundrobin_operation"
  get "inquiry" => "static_pages#inquiry"

  resources :eliminations, except: :index do
    resource :draw, only: [:show], module: :eliminations
    resource :authentication, only: [:new, :create], module: :eliminations
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_eliminations' => 'eliminations#index'

  resources :roundrobins, except: :index do
    resource :draw, only: [:show, :update], module: :roundrobins
    resource :ranking, only: [:show], module: :roundrobins
    resource :authentication, only: [:new, :create], module: :roundrobins
    post :reset, on: :member
    get :share, on: :member
  end
  get 'index_roundrobins' => 'roundrobins#index'

  resources :tournaments, only: [:index] do
    namespace :teams do
      resource :shuffle, only: [:create]
      resource :bulk_update, only: [:create]
    end
    resources :teams, except: :show
    resources :games
    resource :bookmark, only: [:create, :destroy]
  end
end

app/models/elimination.rb
class Elimination < ApplicationRecord
  belongs_to :tournament
  delegate :teams, to: :tournament
  delegate :games, to: :tournament

  validates :name, presence: true, length: { maximum: 16 }
  validates :has_score, inclusion: { in: [true, false] }
  validates :password, length: { maximum: 16 }


  def final_round
    teams.size >= 2 ? Math.log2(teams.length).ceil : 0
  end

  def status
    if games.count == 0
      sts = "NOT_STARTED"
    else
      if games.find_by(round: final_round)
        sts = "FINISHED"
      else
        sts = "ONGOING"
      end
    end

    sts
  end

  def self.seed_table_256
    [
      1, 256, 129, 128, 65, 192, 193, 64, 33, 224, 161, 96, 97, 160, 225, 32,
      17, 240, 145, 112, 81, 176, 209, 48, 49, 208, 177, 80, 113, 144, 241, 16,
      9, 248, 137, 120, 73, 184, 201, 56, 41, 216, 169, 88, 105, 152, 233, 24,
      25, 232, 153, 104, 89, 168, 217, 40, 57, 200, 185, 72, 121, 136, 249, 8,
      5, 252, 133, 124, 69, 188, 197, 60, 37, 220, 165, 92, 101, 156, 229, 28,
      21, 236, 149, 108, 85, 172, 213, 44, 53, 204, 181, 76, 117, 140, 245, 12,
      13, 244, 141, 116, 77, 180, 205, 52, 45, 212, 173, 84, 109, 148, 237, 20,
      29, 228, 157, 100, 93, 164, 221, 36, 61, 196, 189, 68, 125, 132, 253, 4,
      3, 254, 131, 126, 67, 190, 195, 62, 35, 222, 163, 94, 99, 158, 227, 30,
      19, 238, 147, 110, 83, 174, 211, 46, 51, 206, 179, 78, 115, 142, 243, 14,
      11, 246, 139, 118, 75, 182, 203, 54, 43, 214, 171, 86, 107, 150, 235, 22,
      27, 230, 155, 102, 91, 166, 219, 38, 59, 198, 187, 70, 123, 134, 251, 6,
      7, 250, 135, 122, 71, 186, 199, 58, 39, 218, 167, 90, 103, 154, 231, 26,
      23, 234, 151, 106, 87, 170, 215, 42, 55, 202, 183, 74, 119, 138, 247, 10,
      15, 242, 143, 114, 79, 178, 207, 50, 47, 210, 175, 82, 111, 146, 239, 18,
      31, 226, 159, 98, 95, 162, 223, 34, 63, 194, 191, 66, 127, 130, 255, 2
    ]
  end

  # Function


  def seed_table
    return [] if teams.length < 2

    num_of_teams_bye = 2 ** final_round # Team数以上で最小の2のべき乗
    seed_table = self.class.seed_table_256.select { |n| n <= num_of_teams_bye }

    work = []
    num_of_teams_bye.times do |i|
      hash_temp = {}
      hash_temp.store(:seed, seed_table[i])
      hash_temp.store(:round1_gameNo, (i / 2) + 1)
      hash_temp.store(:round1_side, i.even? ? "a" : "b")
      hash_temp.store(:round2_gameNo, (i / 4) + 1)
      hash_temp.store(:round2_side, (i / 2).even? ? "a" : "b")
      work[i] = hash_temp
    end
    work.select { |n| n[:seed] <= teams.size } # Team数を超える文をカット
  end

end

app/controllers/eliminations/authentications_controller.rb
class Eliminations::AuthenticationsController < ApplicationController
  def new
    @elimination = Elimination.find_by(id: params[:elimination_id])
  end

  def create
    @elimination = Elimination.find_by(id: params[:elimination_id])
    unless @elimination
      flash[:warning] = "トーナメントが見つかりません。"
      redirect_to root_path and return
    end

    @error_message = nil
    if @elimination.password == params[:password]
      authenticaion = Authentication.new(cookies)
      authenticaion.set_password(id: @elimination.id, tournament_type: 'elimination', password: params[:password])

      redirect_to elimination_draw_path(@elimination)
    else
      @error_message = "パスワードが不一致です"

      render 'new', status: :unprocessable_entity
    end
  end
end

app/controllers/eliminations/draws_controller.rb
class Eliminations::DrawsController < ApplicationController

  def show
    elimination = Elimination.find_by(id: params[:elimination_id])
    unless elimination
      flash[:warning] = "トーナメントが見つかりません。"
      redirect_to root_path and return
    end
    elimination.tournament.update_last_access_day

    @elimination = EliminationDecorator.new(elimination)
  end

end

app/controllers/eliminations_controller.rb
class EliminationsController < ApplicationController
  before_action :authenticate_owner, only: [:edit, :update, :destroy, :reset]

  def index
    @num_of_eliminations = Elimination.all.size
    @eliminations = Elimination.all.order(created_at: :desc).page(params[:page])
  end

  def show
    redirect_to elimination_draw_path(params[:id])
  end

  def new
    @elimination = Elimination.new
  end

  def create
    ActiveRecord::Base.transaction do
      tournament = Tournament.create(tournament_type: :elimination)
      @elimination = tournament.build_elimination(elimination_params)
      num_of_teams = params[:num_of_teams].to_i

      if @elimination.save
        authenticaion = Authentication.new(cookies)
        authenticaion.set_password(id: @elimination.id, tournament_type: 'elimination', password: @elimination.password)

        (1..num_of_teams).each do |i|
          @elimination.teams.create(name: "Team#{i}", entryNo: i)
        end
        redirect_to elimination_draw_path(@elimination)
      else
        render 'new', status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end
    end
  end

  def edit
    @elimination = Elimination.find_by(id: params[:id])
    unless @elimination
      flash[:warning] = "トーナメントが見つかりません。"
      redirect_to root_path
    end
  end

  def update
    @elimination = Elimination.find_by(id: params[:id])

    if @elimination.update(elimination_params)
      authenticaion = Authentication.new(cookies)
      authenticaion.set_password(id: @elimination.id, tournament_type: 'elimination', password: @elimination.password)

      redirect_to elimination_draw_path(@elimination)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @elimination = Elimination.find_by(id: params[:id])
    @elimination.tournament.destroy
    authenticaion = Authentication.new(cookies)
    authenticaion.clear_password(id: @elimination.id, tournament_type: 'elimination')

    redirect_to root_path, flash: { info: 'トーナメントを削除しました' }
  end

  def reset
    @elimination = Elimination.find_by(id: params[:id])
    @elimination.games.delete_all

    redirect_to elimination_draw_path(@elimination), flash: { info: 'トーナメントをリセットしました' }
  end

  def share
    @elimination = Elimination.find_by(id: params[:id])
  end


  ### Private Method

  private

  def elimination_params
    ret_p = params.require(:elimination).permit(:name, :description, :has_score, :password)
    if ret_p[:name].blank?
      ret_p[:name] = "#{Date.today}"
    end
    ret_p
  end

  def authenticate_owner
    elimination = Elimination.find_by(id: params[:id])
    unless view_context.tournament_owner?(elimination.tournament)
      redirect_to elimination_draw_path(elimination)
    end
  end

end

app/helpers/eliminations_helper.rb
module EliminationsHelper
  include ApplicationHelper

  def border_top_bottom__a_win_b_win(game)
    if (game)
      if (game["a_result"] == 'WIN')
        "r-top"
      elsif (game["b_result"] == 'WIN')
        "r-bottom"
      end
    end
  end

  def border_top__a_win(game)
    if (game)
      if (game["a_result"] == 'WIN')
        "r-top"
      end
    end
  end

  def border_bottom__b_win(game)
    if (game)
      if (game["b_result"] == 'WIN')
        "r-bottom"
      end
    end
  end

  def border_left_bottom__a_win(game)
    if (game)
      if (game["a_result"] == 'WIN')
        "r-left r-bottom"
      end
    end
  end

  def border_left_top__b_win(game)
    if (game)
      if (game["b_result"] == 'WIN')
        "r-left r-top"
      end
    end
  end


end

app/views/eliminations/_bookmark_button.html.erb
<div class="container-lg my-3">
  <div class="d-flex justify-content-end">

    <% if tournament_bookmarked?(tournament_bookmarks, elimination.tournament.id) %>
      <%= button_to(bookmark_off_elimination_path(elimination), class: "btn btn-outline-dark fw-normal") do %>
        <i class="bi bi-star-fill"></i>
        <span class="fw-normal">ブックマーク済</span>
      <% end %>
    <% else %>
      <%= button_to(bookmark_on_elimination_path(elimination), class: "btn btn-outline-dark fw-normal") do %>
        <i class="bi bi-star"></i>
        <span class="fw-normal">ブックマーク</span>
      <% end %>
    <% end %>

  </div>
</div>

app/views/eliminations/_elimination.html.erb
<div class="col-md-6 mb-2">
  <div class="card bg-light">
    <%= link_to elimination_draw_path(elimination), class: "card-body text-decoration-none" do %>
      <div class="d-flex justify-content-between">
        <p class="card-title"><%= elimination.name %>　<%= span_tag__status(elimination) %></p>
        <i class="bi bi-chevron-right"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/eliminations/admin.html.erb
<% set_meta_tags title: @elimination.name, og: { title: @elimination.name } %>

<%# トーナメント共通ヘッダ %>
<%= render "shared/elimination_header", { elimination: @elimination, current_page: "更新" } %>

<div class="container-lg my-3">

  <p> この大会は、作成者にパスワードで保護されています。 </p>
  <div class="border border-dark p-4">
    <%= turbo_frame_tag "form" do %>
      <%= form_with(url: authentication_elimination_path(@elimination), id: "password_form", data: { turbo_frame: "_top" }) do |form| %>
        <%# Error Message %>
        <% if @error_message %>
          <div class="alert alert-danger mb-4">
            <%= @error_message %>
          </div>
        <% end %>

        <%# パスワード %>
        <%= label_tag(:password, "更新パスワード", class: "form-control-label text-dark text-nowrap") %>
        <div class="mb-1 d-flex justify-content-between align-items-center gap-2">

          <div class="">
            <%= text_field_tag(:password, "", class: "form-control") %>
          </div>
          <div class="">
            <%= form.submit('送信', class: "btn btn-secondary") %>
          </div>
        </div>

        <%# Submit %>

      <% end %>
    <% end %>
  </div>
</div>

app/views/eliminations/edit.html.erb
<% set_meta_tags title: @elimination.name, og: { title: @elimination.name } %>

<%# トーナメント共通ヘッダ %>
<%= render "shared/elimination_header", { elimination: @elimination, current_page: "設定" } %>

<div class="container-lg bg-light py-3">
  <%# 変更フォーム %>
  <div class="mb-4">
    <%= form_with(model: @elimination, id: "edit-elimination") do |form| %>
      <%# Error Message %>
      <%= form_error_notification(@elimination) %>

      <%# 大会名 %>
      <div class="mb-4">
        <%= form.label(:name, "大会名", class: "form-control-label") %>
        <%= form.text_field(:name, class: "form-control", placeholder: "(空の場合は、本日の日付が入ります。)") %>
      </div>

      <%# 説明 %>
      <div class="mb-4">
        <%= form.label(:description, "説明", class: "form-control-label") %>
        <%= form.text_area(:description, rows: 5, cols: 10, class: "form-control", placeholder: "(省略可能)") %>
      </div>

      <%# スコア有無 %>
      <div class="form-check mb-4">
        <%= form.check_box :has_score, { class: 'form-check-input' } %>
        <%= form.label :has_score, "スコアを記録", class: "form-check-label" %>
      </div>

      <%# 更新パスワード %>
      <div class="mb-4">
        <%= form.label(:password, "更新パスワード", class: "form-control-label") %>
        <% tooltip_title = "共有する相手に更新を許可しない場合、本パスワードを設定してください。" %>
        <span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title=<%= tooltip_title %>><i class="bi bi-question-square-fill"></i></span>
        <%= form.text_field(:password, class: "form-control", placeholder: "(空の場合は、他のブラウザからも更新可能です。)") %>
      </div>

      <%# 更新ボタン %>
      <div class="d-flex mt-4 justify-content-end">
        <div class="bg-white">
          <%= form.submit("更新", class: "btn btn-outline-main") %>
        </div>
      </div>
    <% end %>
  </div>

  <hr>

  <%# リセット %>
  <div class="mb-4">
    <h5 class="text-danger">トーナメントをリセット</h5>
    <p>試合結果を削除して、トーナメント開始前の状態に戻します。</p>
    <div class="d-flex justify-content-end">
      <div class="bg-white">
        <%= button_to "リセット", reset_elimination_path(@elimination), class: "btn btn-outline-danger",
                      data: { turbo_confirm: "全試合結果を削除します。" } %>
      </div>
    </div>
  </div>

  <hr>

  <%# 削除 %>
  <div class="mb-4">
    <h5 class="text-danger">トーナメントを削除</h5>
    <div class="d-flex justify-content-end">
      <div class="bg-white">
        <%= button_to "削除", elimination_path(@elimination), class: "btn btn-outline-danger",
                      method: :delete,
                      data: { turbo_confirm: "「#{@elimination.name}」トーナメントを削除します。削除すると元には戻せません。" } %>
      </div>
    </div>
  </div>
</div>

app/views/eliminations/index.html.erb
<% set_meta_tags title: 'トーナメント一覧', og: { title: 'トーナメント一覧' } %>

<div class="container-lg my-3">
  <h1 class="mb-4">トーナメント一覧</h1>

  <% if @eliminations.present? %>
    <p class="lead"><%= "トーナメント数: #{@num_of_eliminations}" %></p>
    <div class="row mb-4">
      <%= render @eliminations %>
    </div>
    <div class="d-flex justify-content-center">
      <%= paginate @eliminations, theme: 'bootstrap-5' %>
    </div>
  <% else %>
    <div class="alert alert-warning">トーナメントは未登録です</div>
  <% end %>
</div>

app/views/eliminations/new.html.erb
<% set_meta_tags title: 'トーナメント表作成', og: { title: 'トーナメント表作成' } %>

<div class="container-lg my-3">
  <h1 class="mb-5">トーナメント表作成</h1>
</div>


<div class="container-lg bg-light py-3">

  <%= form_with(model: @elimination, id: "new-elimination") do |form| %>
    <%# Error Message %>
    <%= form_error_notification(@elimination) %>

    <%# 大会名 %>
    <div class="mb-4">
      <%= form.label(:name, "大会名", class: "form-control-label") %>
      <%= form.text_field(:name, class: "form-control", placeholder: "(空の場合は、本日の日付が入ります。)") %>
    </div>

    <%# 説明 %>
<!--    <div class="mb-4">-->
      <%#= form.label(:description, "説明", class: "form-control-label") %>
      <%#= form.text_area(:description, rows: 5, cols: 10, class: "form-control", placeholder: "(省略可能)") %>
<!--    </div>-->

    <%# チーム数 %>
    <div class="mb-4">
      <%= label_tag :num_of_teams, "参加チーム数", class: "form-control-label" %>
      <%= select_tag :num_of_teams, options_for_select(1..MAX_TEAMS, 4), { class: "form-control" } %>
    </div>

    <hr>
    <p class="text-secondary mb-4">
      <span><i class="bi bi-diamond-fill"></i></span>
      詳細設定
    </p>

    <%# スコア有無 %>
    <div class="form-check mb-4">
      <%= form.check_box :has_score, { class: 'form-check-input' } %>
      <%= form.label :has_score, "スコアを記録", class: "form-check-label" %>
    </div>

    <%# 更新パスワード %>
<!--    <div class="mb-4">-->
      <%#= form.label(:password, "更新パスワード", class: "form-control-label") %>
      <%# tooltip_title = "共有する相手に更新を許可しない場合、本パスワードを設定してください。" %>
<!--      <span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title=<%#= tooltip_title %>><i class="bi bi-question-square-fill"></i></span>-->
      <%#= form.text_field(:password, class: "form-control", placeholder: "(空の場合は、他のブラウザからも更新可能です。)") %>
<!--    </div>-->

    <%# 作成ボタン %>
    <div class="d-flex mt-4 justify-content-end">
      <div class="bg-white">
        <%= form.submit("作成", class: "btn btn-outline-main") %>
      </div>
    </div>

  <% end %>
</div>

app/views/eliminations/share.html.erb
<% set_meta_tags title: @elimination.name, og: { title: @elimination.name } %>

<%# トーナメント共通ヘッダ %>
<%= render "shared/elimination_header", { elimination: @elimination, current_page: "共有" } %>

<div class="container-lg my-3">
  <p class="fw-bold">この大会のURL</p>
  <p>後でアクセスするときや、他の人と共有するにはこのURLを使用します。</p>
  <div class="alert alert-light overflow-x-scroll">
    <%= elimination_url(@elimination) %>
  </div>
</div>

app/views/eliminations/show.html.erb
<% set_meta_tags title: @elimination.name, og: { title: @elimination.name } %>

<%# トーナメント共通ヘッダ %>
<%= render "shared/elimination_header", { elimination: @elimination, current_page: "トーナメント表" } %>

<%# Bookmarkボタン %>
<%= turbo_frame_tag "bookmark_button" do %>
  <%= render "bookmarks/bookmark_button", { bookmarked_tournaments: @bookmarked_tournament_ids, tournament: @elimination.tournament } %>
<% end %>


<%# トーナメント説明 %>
<% if @elimination.description.present? %>
  <div class="bg-light my-5">
    <div class="container-lg py-3">
      <p class="pre-wrap"><%= raw Rinku.auto_link(@elimination.description, :urls, 'target="_blank" rel="noopener noreferrer"') %></p>
    </div>
  </div>
<% end %>

<%# 参加チームなしの場合 %>
<% if @teams.count < 2 %>
  <div class="container-lg my-3">
    <div class="alert alert-warning">参加チームが2チーム以上必要です</div>
  </div>

<% else %>
  <%# 更新方法説明 (パスワード保護解除時のみ) %>
  <% if tournament_owner?(@elimination.tournament) %>
    <div class="container-lg">
      <p>
        <!--                <i class="bi bi-info-circle" style="color: goldenrod"></i>-->
        各試合をクリックして、試合結果を更新します。
        <% tooltip_title = "下のトーナメント表の各試合(薄い黄色部分)をクリック" %>
        <span data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title=<%= tooltip_title %>>
          <i class="bi bi-question-square-fill"></i>
        </span>
      </p>
    </div>
  <% end %>

  <div class="bg-white border-0 border-dark py-3">
    <div id="elimination-table-wrapper" class="container-lg elimination-table-wrapper">
      <%= render partial: "eliminations/main_race",
                 locals: { elimination: @elimination, teams: @teams, games: @games, round_offset: 0, final_round: @elimination.final_round, seed_table: @elimination.seed_table } %>
    </div>
  </div>

  <%= turbo_frame_tag "modal" %>
<% end %>